import { Outfit, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import AppWrapper from "./context/AppWrapper";
import NavSidebar from "@/components/NavSidebar";
import LenisWrapper from "@/components/LenisWrapper";
import Footer from "@/components/Footer";


const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-outfit",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Plumbing-X",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LenisWrapper>
          <AppWrapper>
            <Header />
            <NavSidebar />
            {children}
            <Footer />
          </AppWrapper>
        </LenisWrapper>
      </body>
    </html>
  );
}
